### ISSUE TITLE
Should QNNs be able to handle lists as y values for fitting?

### ISSUE THREAD

**Issue by rothma** [sQUlearn/squlearn#113]
I guess this is something we want?

```
Unexpected exception formatting exception. Falling back to standard exception
Traceback (most recent call last):
  File "c:\Users\mcr\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\mcr\AppData\Local\Temp\ipykernel_19772\793130201.py", line 16, in <cell line: 16>
    reg.fit(X_train, Y_train)
  File "C:\Users\mcr\PycharmProjects\squlearn\src\squlearn\qnn\base_qnn.py", line 114, in fit
    self._fit(X, y, weights)
  File "C:\Users\mcr\PycharmProjects\squlearn\src\squlearn\qnn\qnnr.py", line 212, in _fit
  File "C:\Users\mcr\PycharmProjects\squlearn\src\squlearn\qnn\qnnr.py", line 185, in partial_fit
    self._qnn,
  File "C:\Users\mcr\PycharmProjects\squlearn\src\squlearn\qnn\training.py", line 521, in regression
    elif weights is None:
AttributeError: 'list' object has no attribute 'shape'
```

**Comment by MoritzWillmann** [comment]
Can sklearn hlms do this? If yes, yes.
