### ISSUE TITLE
Cannot import sQUlearn due to use of outdated package `scikit-optimize`

### ISSUE THREAD

**Issue by MoritzWillmann** [sQUlearn/squlearn#267]
**Describe the bug**
After `scikit-learn` got updated to 1.5.0, the function `sklearn.utils.check_pandas_support` got moved to a separate module `sklearn.utils._optional_dependencies.check_pandas_support`. `scikit-optimize` uses this function internally. The problem is, that `scikit-optimize` isn't maintained anymore and this issue won't be fixed.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mow\Documents\AutoQML\squlearn\src\squlearn\__init__.py", line 4, in <module>
    from . import observables, encoding_circuit, kernel, optimizers, qnn, util
  File "C:\Users\mow\Documents\AutoQML\squlearn\src\squlearn\kernel\__init__.py", line 1, in <module>
    from . import matrix, ml, optimization
  File "C:\Users\mow\Documents\AutoQML\squlearn\src\squlearn\kernel\matrix\__init__.py", line 2, in <module>
    from .projected_quantum_kernel import ProjectedQuantumKernel
  File "C:\Users\mow\Documents\AutoQML\squlearn\src\squlearn\kernel\matrix\projected_quantum_kernel.py", line 22, in <module>
    from ...qnn.lowlevel_qnn import LowLevelQNN
  File "C:\Users\mow\Documents\AutoQML\squlearn\src\squlearn\qnn\__init__.py", line 4, in <module>
    from .qnnc import QNNClassifier
  File "C:\Users\mow\Documents\AutoQML\squlearn\src\squlearn\qnn\qnnc.py", line 11, in <module>
    from .base_qnn import BaseQNN
  File "C:\Users\mow\Documents\AutoQML\squlearn\src\squlearn\qnn\base_qnn.py", line 15, in <module>
    from ..optimizers.optimizer_base import OptimizerBase, SGDMixin
  File "C:\Users\mow\Documents\AutoQML\squlearn\src\squlearn\optimizers\__init__.py", line 4, in <module>
    from .sglbo import SGLBO
  File "C:\Users\mow\Documents\AutoQML\squlearn\src\squlearn\optimizers\sglbo.py", line 3, in <module>
    from skopt import gp_minimize
  File "C:\Users\mow\Documents\AutoQML\squlearn\venv\lib\site-packages\skopt\__init__.py", line 21, in <module>
    from . import (
  File "C:\Users\mow\Documents\AutoQML\squlearn\venv\lib\site-packages\skopt\callbacks.py", line 18, in <module>
    from skopt.utils import dump, load
  File "C:\Users\mow\Documents\AutoQML\squlearn\venv\lib\site-packages\skopt\utils.py", line 20, in <module>
    from .sampler import Grid, Halton, Hammersly, InitialPointGenerator, Lhs, Sobol
  File "C:\Users\mow\Documents\AutoQML\squlearn\venv\lib\site-packages\skopt\sampler\__init__.py", line 3, in <module>
    from .lhs import Lhs
  File "C:\Users\mow\Documents\AutoQML\squlearn\venv\lib\site-packages\skopt\sampler\lhs.py", line 11, in <module>
    from ..space import Space
  File "C:\Users\mow\Documents\AutoQML\squlearn\venv\lib\site-packages\skopt\space\__init__.py", line 3, in <module>
    from .space import *
  File "C:\Users\mow\Documents\AutoQML\squlearn\venv\lib\site-packages\skopt\space\space.py", line 8, in <module>
    from sklearn.utils import check_pandas_support, check_random_state
ImportError: cannot import name 'check_pandas_support' from 'sklearn.utils' (C:\Users\mow\Documents\AutoQML\squlearn\venv\lib\site-packages\sklearn\utils\__init__.py)
```

This is why we need to find an alternative to `scikit-optimize` ASAP.

**To Reproduce**
Try to import sQUlearn
```
import squlearn
```

**Expected behavior**
Import sQUlearn

cc. @DennisKleinhans (can you maybe have a look at this?)

**Comment by MoritzWillmann** [comment]
As a workaround until this issue is fixed, please install `scikit-learn<1.5.0` manually.
