### ISSUE TITLE
qiskit version requirement

### ISSUE THREAD

**Issue by MazenAli** [sQUlearn/squlearn#299]
The qiskit requirement `"qiskit>=0.43.0,<1.1.0"` in `pyproject.toml` is incompatible with pre-stable release versions of qiskit (the rest of the qiskit packages are 0.x) and with itself (1.0 is not backwards compatible with 0.x). Maybe change to `"qiskit>=0.43.0,<1.0"`?

Generally, the version requirements for all packages are too loose and do not ensure backwards compatibility.

Error on my device:

```bash
Traceback (most recent call last):
  File "/opt/project/use_case/examples/qkrenelgeo.py", line 8, in <module>
    from squlearn import Executor
  File "/usr/local/lib/python3.9/site-packages/squlearn/__init__.py", line 3, in <module>
    from .util import Executor
  File "/usr/local/lib/python3.9/site-packages/squlearn/util/__init__.py", line 1, in <module>
    from .executor import Executor
  File "/usr/local/lib/python3.9/site-packages/squlearn/util/executor.py", line 15, in <module>
    import qiskit
  File "/usr/local/lib/python3.9/site-packages/qiskit/__init__.py", line 36, in <module>
    raise ImportError(
ImportError: Qiskit is installed in an invalid environment that has both Qiskit >=1.0 and an earlier version. You should create a new virtual environment, and ensure that you do not mix dependencies between Qiskit <1.0 and >=1.0. Any packages that depend on 'qiskit-terra' are not compatible with Qiskit 1.0 and will need to be updated. Qiskit unfortunately cannot enforce this requirement during environment resolution. See https://qisk.it/packaging-1-0 for more detail.
```

Installed libs and versions

```bash
qiskit                  1.0.2
qiskit-aer              0.14.2
qiskit-algorithms       0.3.1
qiskit-ibm-runtime      0.23.0
qiskit-machine-learning 0.6.1
qiskit-terra            0.46.3
QuantLib                1.33
requests                2.32.3
requests_ntlm           1.3.0
rustworkx               0.15.1
scikit-learn            1.0.2
scipy                   1.13.1
seaborn                 0.12.2
setuptools              58.1.0
six                     1.16.0
smmap                   5.0.1
squlearn                0.7.6
```

**Comment by MazenAli** [comment]
Hi David. I can fix the issue myself, ofc, by manually installing and deinstalling until it works, but that's not the point. Out of the box pip install in a clean docker environment does not guarantee a runnable `squlearn` because of version numbers incompatibilities.

**Comment by David-Kreplin** [comment]
Yes, it looks like we haven't updated the requirements in a while; qiskit-machine-learning>=0.7.0 is definitely required.
There is also a version conflict with the latest update addressing the issue with Bayesian optimization (see #300).
So far, pip install has always worked for us (also in different docker set-ups), which is why we haven't done extensive testing on the dependencies.
We will try to fix everything in the next release this week, and we should add a test job for the lowest requirements.

In general, if you'd like to contribute, we appreciate any support and contributions!

**Comment by David-Kreplin** [comment]
We are still unsure how you could end up with both qiskit-terra and qiskit==1.0.2 installed in the same environment. The only explanation we have is that there might be some automatic dependency resolution running in the background.

If qiskit <1.0 is installed first and later upgraded to qiskit >1.0, this could lead to such an environment. Unfortunately, this issue cannot be resolved by simply adjusting our dependencies. It appears that qiskit can only work with either qiskit >=0.43.0, <1.0 or qiskit >=1.0. To run everything on IBM Quantum, we are required to upgrade to the 1.x version.

**Comment by MazenAli** [comment]
Here is another example before and after a fresh install. Before adding `squlearn` to requirements, this is my pip list:

```bash
bandit            1.7.10
black             24.3.0
click             8.1.7
coverage          7.6.4
cycler            0.12.1
exceptiongroup    1.2.2
flake8            7.1.1
fonttools         4.54.1
iniconfig         2.0.0
isort             5.13.2
jax               0.4.35
jaxlib            0.4.35
joblib            1.4.2
kiwisolver        1.4.7
markdown-it-py    3.0.0
matplotlib        3.5.3
mccabe            0.7.0
mdurl             0.1.2
ml_dtypes         0.5.0
mypy              1.13.0
mypy-extensions   1.0.0
numpy             1.26.3
opt_einsum        3.4.0
packaging         24.1
pandas            1.3.5
pathspec          0.12.1
pbr               6.1.0
pillow            11.0.0
pip               24.2
platformdirs      4.3.6
pluggy            1.5.0
pycodestyle       2.12.1
pyflakes          3.2.0
Pygments          2.18.0
pyparsing         3.2.0
pytest            8.3.3
python-dateutil   2.9.0.post0
pytz              2024.2
PyYAML            6.0.2
QuantLib          1.33
rich              13.9.3
scikit-learn      1.0.2
scipy             1.14.1
seaborn           0.12.2
setuptools        65.5.1
six               1.16.0
stevedore         5.3.0
teneva            0.14.9
teneva-jax        0.1.1
threadpoolctl     3.5.0
tomli             2.0.2
torch             1.13.1
torchTT           2.0
typing_extensions 4.12.2
wheel             0.44.0
```


After adding `squlearn` and rebuilding from scratch:



```bash
annotated-types         0.7.0
appdirs                 1.4.4
autograd                1.7.0
autoray                 0.7.0
bandit                  1.7.10
bayesian-optimization   2.0.0
black                   24.3.0
cachetools              5.5.0
certifi                 2024.8.30
cffi                    1.17.1
charset-normalizer      3.4.0
click                   8.1.7
colorama                0.4.6
coverage                7.6.4
cryptography            43.0.3
cycler                  0.12.1
dill                    0.3.9
exceptiongroup          1.2.2
fastdtw                 0.3.4
flake8                  7.1.1
fonttools               4.54.1
ibm-cloud-sdk-core      3.22.0
ibm-platform-services   0.57.2
idna                    3.10
iniconfig               2.0.0
isort                   5.13.2
jax                     0.4.35
jaxlib                  0.4.35
joblib                  1.4.2
kiwisolver              1.4.7
markdown-it-py          3.0.0
matplotlib              3.5.3
mccabe                  0.7.0
mdurl                   0.1.2
ml_dtypes               0.5.0
mpmath                  1.3.0
mypy                    1.13.0
mypy-extensions         1.0.0
networkx                3.4.2
numpy                   1.26.3
opt_einsum              3.4.0
packaging               24.1
pandas                  1.3.5
pathspec                0.12.1
pbr                     6.1.0
PennyLane               0.38.0
PennyLane_Lightning     0.38.0
pillow                  11.0.0
pip                     24.2
platformdirs            4.3.6
pluggy                  1.5.0
ply                     3.11
psutil                  6.1.0
pycodestyle             2.12.1
pycparser               2.22
pydantic                2.9.2
pydantic_core           2.23.4
pyflakes                3.2.0
Pygments                2.18.0
PyJWT                   2.9.0
pyparsing               3.2.0
pyspnego                0.11.1
pytest                  8.3.3
python-dateutil         2.9.0.post0
pytz                    2024.2
PyYAML                  6.0.2
qiskit                  1.0.2
qiskit-aer              0.14.2
qiskit-algorithms       0.3.1
qiskit-ibm-runtime      0.23.0
qiskit-machine-learning 0.6.1
qiskit-terra            0.46.3
QuantLib                1.33
requests                2.32.3
requests_ntlm           1.3.0
rich                    13.9.3
rustworkx               0.15.1
scikit-learn            1.0.2
scipy                   1.14.1
seaborn                 0.12.2
setuptools              65.5.1
six                     1.16.0
squlearn                0.7.6
stevedore               5.3.0
symengine               0.13.0
sympy                   1.13.3
teneva                  0.14.9
teneva-jax              0.1.1
threadpoolctl           3.5.0
toml                    0.10.2
tomli                   2.0.2
torch                   1.13.1
torchTT                 2.0
tqdm                    4.66.5
typing_extensions       4.12.2
urllib3                 2.2.3
websocket-client        1.8.0
wheel                   0.44.0
```

With the resulting error when trying to import `squlearn` as before. The issue is definitely not a pre-existing `qiskit` install.

**Comment by MazenAli** [comment]
What currently works for me (at least to build and import) is adding this explicitly to the requirements

```python
qiskit~=0.43
qiskit-machine-learning~=0.7
bayesian-optimization~=1.4
squlearn~=0.7
```

which results in

```bash
bayesian-optimization   1.5.1
qiskit                  0.46.3
qiskit-aer              0.14.2
qiskit-algorithms       0.3.1
qiskit-ibm-runtime      0.20.0
qiskit-machine-learning 0.7.2
qiskit-terra            0.46.3
```

**Comment by David-Kreplin** [comment]
Ok, interesting.
What happens if you add qiskit==1.1 instead of squlearn to the requirements file?
It looks to me like there's a dependency conflict that it's trying to resolve, leading to different versions of Qiskit being installed, which results in both qiskit-terra and qiskit==1.0.2 being installed.

**Comment by MazenAli** [comment]
Removed `squlearn`, added `qiskit==1.1` instead. My pip list now:

```bash
bandit                  1.7.10
bayesian-optimization   1.5.1
black                   24.3.0
click                   8.1.7
colorama                0.4.6
contourpy               1.3.0
coverage                7.6.4
cycler                  0.12.1
dill                    0.3.9
exceptiongroup          1.2.2
fastdtw                 0.3.4
flake8                  7.1.1
fonttools               4.54.1
iniconfig               2.0.0
isort                   5.13.2
jax                     0.4.35
jaxlib                  0.4.35
joblib                  1.4.2
kiwisolver              1.4.7
markdown-it-py          3.0.0
matplotlib              3.9.2
mccabe                  0.7.0
mdurl                   0.1.2
ml_dtypes               0.5.0
mpmath                  1.3.0
mypy                    1.13.0
mypy-extensions         1.0.0
numpy                   1.26.4
opt_einsum              3.4.0
packaging               24.1
pandas                  1.5.3
pathspec                0.12.1
pbr                     6.1.0
pillow                  11.0.0
pip                     24.2
platformdirs            4.3.6
pluggy                  1.5.0
psutil                  6.1.0
pycodestyle             2.12.1
pyflakes                3.2.0
Pygments                2.18.0
pylatexenc              2.10
pyparsing               3.2.0
pytest                  8.3.3
python-dateutil         2.9.0.post0
pytz                    2024.2
PyYAML                  6.0.2
qiskit                  1.1.0
qiskit-algorithms       0.3.1
qiskit-machine-learning 0.7.2
QuantLib                1.36
rich                    13.9.3
rustworkx               0.15.1
scikit-learn            1.5.2
scipy                   1.14.1
seaborn                 0.13.2
setuptools              65.5.1
six                     1.16.0
stevedore               5.3.0
symengine               0.13.0
sympy                   1.13.3
teneva                  0.14.9
teneva-jax              0.1.1
threadpoolctl           3.5.0
tomli                   2.0.2
torch                   1.13.1
torchTT                 2.0
typing_extensions       4.12.2
wheel                   0.44.0
```

(no `qiskit-terra`)

**Comment by David-Kreplin** [comment]
Ok, so plain Qiskit is not causing the problem. We will check different Squlearn dependencies tomorrow. Thank you very much for providing the requirements; with that information, it should be possible to find the origin of the problem.

**Comment by David-Kreplin** [comment]
Running your Docker (without the sQUlearn package and 

With a changed ``requirements.txt`` (without the squlearn stuff):

```
torch~=1.13
numpy~=1.26
pandas~=1.3
matplotlib~=3.5
scikit-learn~=1.0
seaborn~=0.12
QuantLib~=1.33
scipy
teneva
teneva-jax
```

Afterwards I install squlearn with ``pip install squlearn``.

A pip freeze call returns (no conflicts)

```
annotated-types==0.7.0
appdirs==1.4.4
autograd==1.7.0
autoray==0.7.0
bandit==1.7.10
bayesian-optimization==2.0.0
black==24.3.0
cachetools==5.5.0
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.4.0
click==8.1.7
colorama==0.4.6
contourpy==1.3.0
coverage==7.6.4
cryptography==43.0.3
cycler==0.12.1
dill==0.3.9
exceptiongroup==1.2.2
fastdtw==0.3.4
flake8==7.1.1
fonttools==4.54.1
ibm-cloud-sdk-core==3.22.0
ibm-platform-services==0.58.0
idna==3.10
iniconfig==2.0.0
isort==5.13.2
jax==0.4.35
jaxlib==0.4.35
joblib==1.4.2
kiwisolver==1.4.7
markdown-it-py==3.0.0
matplotlib==3.9.2
mccabe==0.7.0
mdurl==0.1.2
ml_dtypes==0.5.0
mpmath==1.3.0
mypy==1.13.0
mypy-extensions==1.0.0
networkx==3.4.2
numpy==1.26.4
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
opt_einsum==3.4.0
packaging==24.1
pandas==1.5.3
pathspec==0.12.1
pbr==6.1.0
PennyLane==0.38.0
PennyLane_Lightning==0.38.0
pillow==11.0.0
platformdirs==4.3.6
pluggy==1.5.0
psutil==6.1.0
pycodestyle==2.12.1
pycparser==2.22
pydantic==2.9.2
pydantic_core==2.23.4
pyflakes==3.2.0
Pygments==2.18.0
PyJWT==2.9.0
pyparsing==3.2.0
pyspnego==0.11.1
pytest==8.3.3
python-dateutil==2.9.0.post0
pytz==2024.2
PyYAML==6.0.2
qiskit==1.0.2
qiskit-aer==0.14.2
qiskit-algorithms==0.3.1
qiskit-ibm-runtime==0.23.0
qiskit-machine-learning==0.7.2
QuantLib==1.36
requests==2.32.3
requests_ntlm==1.3.0
rich==13.9.3
rustworkx==0.15.1
scikit-learn==1.4.1.post1
scipy==1.14.1
seaborn==0.13.2
six==1.16.0
squlearn==0.7.6
stevedore==5.3.0
symengine==0.13.0
sympy==1.13.3
teneva==0.14.9
teneva-jax==0.1.1
threadpoolctl==3.5.0
toml==0.10.2
tomli==2.0.2
torch==1.13.1
torchTT @ git+https://github.com/ion-g-ion/torchTT@541d9de4bc020d0a4185786f59199724a488e76e
tqdm==4.66.5
typing_extensions==4.12.2
urllib3==2.2.3
websocket-client==1.8.0
```

Interesstingly, no qiskit-terra installation. 

While running the squlearn install I got:

```
Downloading qiskit_ibm_runtime-0.30.0-py3-none-any.whl.metadata (19 kB)
Downloading qiskit_ibm_runtime-0.29.1-py3-none-any.whl.metadata (19 kB)
Downloading qiskit_ibm_runtime-0.29.0-py3-none-any.whl.metadata (19 kB)
Downloading qiskit_ibm_runtime-0.28.0-py3-none-any.whl.metadata (19 kB)
Downloading qiskit_ibm_runtime-0.27.1-py3-none-any.whl.metadata (19 kB)
Downloading qiskit_ibm_runtime-0.27.0-py3-none-any.whl.metadata (19 kB)
Downloading qiskit_ibm_runtime-0.26.0-py3-none-any.whl.metadata (19 kB)
Downloading qiskit_ibm_runtime-0.25.0-py3-none-any.whl.metadata (19 kB)
Downloading qiskit_ibm_runtime-0.24.1-py3-none-any.whl.metadata (19 kB)
Downloading qiskit_ibm_runtime-0.24.0-py3-none-any.whl.metadata (19 kB)
Downloading qiskit_ibm_runtime-0.23.0-py3-none-any.whl.metadata (19 kB)
```  
Looks like there is a dependency problem with qiskit_ibm_runtime and the installed requirements. 

We finally fixed our minimal requirements, they are also now tested. 
Update is comming today or tomorrow.

**Comment by MoritzWillmann** [comment]
Hey @MazenAli, it seems to me like this issue has been resolved. If you have any further questions, don't hesitate to contact us. Cheers Moritz
